name: LibCore
main: com.fyxridd.lib.core.CorePlugin
version: 0.1.0
load: startup
depend: [Vault, ProtocolLib, PacketWrapper]
softdepend: [LibChatShow]
commands:
  f:
    description: FuncManager
    usage: /<command> ?
  s:
    description: InputManager
    usage: /<command> ?
  stop:
    description: none
    usage: /<command> ?